### ISSUE TITLE
Chat example is not working because of nano.ListenWS( ) is not defined

### ISSUE THREAD

**Issue by RonnanSouza** [lonng/nano#47]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do? If possible, provide a recipe for reproducing the error.
I Tried to run the chat example, using `go run main.go` but it wasn't possible because of the `nano.ListenWS` is no longer available.

### 2. What did you expect to see?
Chat example running

### 3. What did you see instead?
`./main.go:153:2: undefined: nano.ListenWS`

### 4. Versions of the `nano`
I cloned the repository at 2019-08029, not sure the version.

**Comment by RonnanSouza** [comment]
I just opened a [PR](https://github.com/lonng/nano/pull/48) fixing this, please review that for me 👍

**Comment by lonng** [comment]
@RonnanSouza Thanks
