### ISSUE TITLE
In Get Started

### ISSUE THREAD

**Issue by tetrahedronix** [lonng/nano#50]
In Get Started the following methods are undefined: OnSessionClosed, Register, SetSerializer, EnableDebug. 

```
undefined: nano.OnSessionClosed
undefined: nano.Register
undefined: nano.SetSerializer
undefined: nano.EnableDebug
```

Then the example uses methods from both chat and cluster packages without import them.

**Comment by lonng** [comment]
@tetravalence The latest version contains some breaking changes, please update the `nano` to the latest version and use the new version interface(reference demo).
