### ISSUE TITLE
连接池部分貌似是只取不放？

### ISSUE THREAD

**Issue by harlanc** [lonng/nano#53]
还有是否有多个连接使用一个grpc.ClientConn 的问题？难道是我没看懂代码？

**Comment by lonng** [comment]
这个是固定连接池，round trip 去取。

**Comment by harlanc** [comment]
连接池有10个ClientConn ，如果有11个Conn请求不会有问题么？

**Comment by lonng** [comment]
不会

**Comment by harlanc** [comment]
多谢，我再看看代码
