### ISSUE TITLE
Handshake Package 中如何自定义握手数据验证

### ISSUE THREAD

**Issue by NicholasChan1025** [lonng/nano#68]
Handshake Package 中如何自定义握手数据验证

client demo和文档中有出现
`{
  "sys": {
    "version": "1.1.1",
    "type": "js-websocket"
  },
  "user": {
    // Any customized request data
  }
}`
的描述
code - 握手响应的状态码。目前的取值：200代表成功，500为处理用户自定义握手流程时失败，501为客户端版 本号不符合要求。
sys.heartbeat - 可选，心跳时间间隔，单位为秒，没指定表示不需要心跳。
dict - 可选，route字段压缩的映射表，没指定表示没有字典压缩。
protos - 可选，protobuf压缩的数据定义，没有表示没有protobuf压缩。
user - 可选，用户自定义的握手数据，没有表示没有用户自定义的握手数据。

服务端关于user的数据如何验证？

**Comment by lonng** [comment]
这部分没有具体实现，你目前有这个需求吗？

**Comment by NicholasChan1025** [comment]
有的，目前是我自己改了源码

**Comment by lonng** [comment]
可以，能提交上来吗？

**Comment by lonng** [comment]
`nano.WithHandshakeValidator` 这个名字可能好一些

**Comment by NicholasChan1025** [comment]
好的
