### ISSUE TITLE
Detect rpc call success 

### ISSUE THREAD

**Issue by xiviu123** [lonng/nano#70]
Hi,
```
if err := s.RPC("TopicService.NewUser", request); err != nil {
		return errors.Trace(err)
	}
```

above code is in cluster example.
How can i check ``` TopicService.NewUser ``` is success or error.
Currenty error is traced only when the TopicService down

thank you.

**Comment by lonng** [comment]
Because the RPC is an async, so you cannot detect the state directly.
A workaround:
1. Record the `TopicService.NewUser` in the current service
2. Delete the record when the `TopicService.NewUser` has a successful callback.

**Comment by xiviu123** [comment]
My game has 2 separatelly services, 

> userservice state all user.

> room service state all room game



In my case, i want to sync user state ( ex :coin) when the match  in room game finished .
With rpc call ,i'm not sure the user state is updated to userservice



Hope your help. Thank you.

**Comment by lonng** [comment]
@xiviu123 Are you using Wechat? Or other IMs?

**Comment by xiviu123** [comment]
Skype or telegram, Which one do you use?

**Comment by lonng** [comment]
@xiviu123 I am sorry, I don't use that IMs. I will give you a demo on how to achieve your requirements.

```go


type (
	// GameService represents a game manager which running on game server instance
	GameService struct {
		Matches map[int]*Match
	}

	// UserSrevice runs on user server instance
	UserSrevice struct {
		// Fileds
	}

	Player struct{
		PlayerID int64
		Session  *session.Session
	}

	Match struct {
		MatchID int64
		Players []*Player
		Status  string
	}

	SettleRequest struct {
		Changes map[int64]int64 // player id -> coin change
	}

	// SettleFinished represents the settle status
	SettleResult struct {
		MatchID int64
	}
)

func (s *GameService) OnGameOver(m *Match) {
	req := &SettleRequest{}	
	for _, p := range m.Players {
		// The coin changes depends on the game result
		req.Changes[p.PlayerID] = 1000
	}
	if err := s.RPC("UserService.Settle", req); err != nil {
		// log
		return
	}
	m.Status = "settle"
}

func (s *GameService) OnSettleFinished(r *SettleResult) {
	m := s.Matches[r.MatchID]
	m.Status = "done"
}

////////////

func (s *UserService) Settle(s *session.Session, r *SettleRequest) {
	// Bussiness logic
	s.RPC("GameService.OnSettleFinished", &SettleResult{MatchID: r.MatchID})
}
```

**Comment by xiviu123** [comment]
@lonng , thank you very much
